CAc:
  abbreviation: CAc
  title: Expositio Actuum Apostolorum
  editions:
    giles: 1.184-86 and 12.1-95
CAcN:
  abbreviation: CAcN
  title: Expositio nominum locorum in Actus contentorum
  editions: {}
CAcR:
  abbreviation: CAcR
  title: Retractatio in Actus Apostolorum
  editions: 
    giles: 1.187-88 and 12.96-156
CAp:
  abbreviation: CAp
  title: Expositio Apocalypseos
  editions:
    giles: 12.337-452
CC:
  abbreviation: CC
  title: In Cantica Canticorum
  editions: 
    giles: 9.188-404
CEC:
  abbreviation: CEC
  title: In epistulas VII catholicas
  editions: 
    giles: 1.215-16 and 12.157-336
CEP:
  abbreviation: CEP
  title: Collectio ex opusculis sancti Augustini in epistulas Pauli
  editions: []
CEz:
  abbreviation: CEz
  title: In Ezram et Neemiam
  editions: 
    giles: 8.360-463 and 9.1-52
CGH:
  abbreviation: CGH
  title: In principium Genesis (Ia only)
  editions: []
CGL:
  abbreviation: CGL
  title: In principium Genesis (long vers. in four books)
  editions:
    giles: 1.169-70 and 7.1-224
CGS:
  abbreviation: CGS
  editions: []
  title: In principium Genesis (short vers. = Ia+Ib)
CH:
  abbreviation: CH
  title: Expositio in Canticam Habacuc
  editions: 
    - giles: 9.405-44
CI:
  abbreviation: CI
  title: De eo quod ait Isaias
  editions: 
    - giles: 1.203-14
CL:
  abbreviation: CL
  title: In Lucae euangelium expositio
  editions: 
    - giles: 1.179-83, 10.265-407, 11.1-392
CM:
  abbreviation: CM
  title: In Marci euangelium expositio
  editions: 
    - giles: 1.176 and 10.1-264
CMF:
  abbreviation: CMF
  title: De mansionibus filiorum Israel
  editions: 
    - giles: 1.198-202
CPr:
  abbreviation: CPr
  title: In Prouerbia Salemonis
  editions: 
    - giles: 9.53-185
CPs:
  abbreviation: CPs
  title: Collectio Psalterii
  editions: {}
CQO:
  abbreviation: CQO
  title: De octo quaestionibus
  editions: {}
CQT:
  abbreviation: CQT
  title: In Regum librum XXX quaestiones
  editions: 
    - giles: 1.174-75 and 8.232-61
CS:
  abbreviation: CS
  title: In primam partem Samuhelis
  editions: 
    - giles: 7.368-432 and 8.1-231
CTa:
  abbreviation: CTa
  title: De tabernaculo
  editions: 
    - giles: 7.225-367
CTe:
  abbreviation: CTe
  title: De templo
  editions: 
    - giles: 1.171-73 and 8.262-359
CTo:
  abbreviation: CTo
  title: In librum beati patris Tobiae
  editions: []
ChMa:
  abbreviation: ChMa
  title: Chronica maiora
  editions: 
    - giles: 6.270-342
ChMi:
  abbreviation: ChMi
  title: Chronica minora
  editions: 
    - giles: 6.132-38
DAM:
  abbreviation: DAM
  title: De arte metrica
  editions: 
    - giles: 6.40-79
DLS:
  abbreviation: DLS
  title: De locis sanctis
  editions: 
    - giles: 4.402-443
DNR:
  abbreviation: DNR
  title: De natura rerum
  editions: 
    - giles: 6.99-122
DO:
  abbreviation: DO
  title: De orthographia
  editions: 
    - giles: 6.1-39
DST:
  abbreviation: DST
  title: De schematibus et tropis
  editions: 
    - giles: 6.80-98
DT:
  abbreviation: DT
  title: De temporibus
  editions: 
    - giles: 6.123-38
DTR:
  abbreviation: DTR
  title: De temporum ratione
  editions: 
    - giles: 6.139-352
EpA:
  abbreviation: EpA
  title: Epistula ad Albinum
  editions: 
    - giles: '1.106-7'
EpE:
  abbreviation: EpE
  title: Epistula ad Ecgbertum
  editions: 
    - giles: 1.108-143
EpH:
  abbreviation: EpH
  title: Epistula ad Helmuualdum
  editions: []
EpP:
  abbreviation: EpP
  title: Epistula ad Pleguinum
  editions: 
    - giles: 1.144-154
EpW:
  abbreviation: EpW
  title: Epistula ad Uuicthedum
  editions: 
    - giles: 1.155-168
H:
  abbreviation: H
  title: Homiliae euangelii
  editions: 
    - giles: 5.1-464
HAB:
  abbreviation: HAB
  title: Historia abbatum
  editions: 
    - giles: 4.358-401
HE:
  abbreviation: HE
  title: Historia ecclesiastica gentis Anglorum
  notes: Giles 2.25-26 superseded by 3.s447-48
  editions: 
    - giles: 2.22-397 and 3.4-319 (odd) 
M:
  abbreviation: M
  title: Martyrologium
  editions: 
    - giles: 4.16-172
P:
  abbreviation: P
  title: Poems
  editions: {}
VA:
  abbreviation: VA
  title: Passio Anastasii
  editions: {}
VCM:
  abbreviation: VCM
  title: Vita Cuthberti metrica
  editions: 
    - giles: 1.1-34
VCP:
  abbreviation: VCP
  title: Vita Cuthberti prosaica
  editions: 
    - giles: 4.202-357
VF:
  abbreviation: VF
  title: Vita Felicis
  editions: 
    - giles: 4.174-201
