CAc:
  abbreviation: CAc
  editions: 
    - giles: '1.184-86 and '
  title: Expositio Actuum Apostolorum
CAcN:
  abbreviation: CAcN
  giles: ''
  heerwagen: ''
  migne: ''
  title: Expositio nominum locorum in Actus contentorum
CAcR:
  abbreviation: CAcR
  editions: 
    - giles: '1.187-88 and '
  heerwagen: ''
  migne: ''
  title: Retractatio in Actus Apostolorum
CAp:
  abbreviation: CAp
  editions:
    - giles: ''
  heerwagen: ''
  migne: ''
  title: Expositio Apocalypseos
CC:
  abbreviation: CC
  editions: 
    - giles: 9.188-404
  title: In Cantica Canticorum
CEC:
  abbreviation: CEC
  editions: 
    - giles: '1.215-16 and '
  heerwagen: ''
  migne: ''
  title: In epistulas VII catholicas
CEP:
  abbreviation: CEP
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: Collectio ex opusculis sancti Augustini in epistulas Pauli
CEz:
  abbreviation: CEz
  editions: 
    - giles: 8.360-463 and 9.1-52
  title: In Ezram et Neemiam
CGH:
  abbreviation: CGH
  editions: []
  title: In principium Genesis (Ia only)
CGL:
  abbreviation: CGL
  editions: 
    - giles: 1.169-70 and 7.1-224
  title: In principium Genesis (long version, = four books)
CGS:
  abbreviation: CGS
  editions: []
  title: In principium Genesis (short vers. = Ia+Ib)
CH:
  abbreviation: CH
  editions: 
    - giles: 9.405-44
  title: Expositio in Canticam Habacuc
CI:
  abbreviation: CI
  editions: 
    - giles: '1.203-14'
  heerwagen: ''
  migne: ''
  title: De eo quod ait Isaias
CL:
  abbreviation: CL
  editions: 
    - giles: '1.179-83 and'
  heerwagen: ''
  migne: ''
  title: In Lucae euangelium expositio
CM:
  abbreviation: CM
  editions: 
    - giles: '1.176 and '
  heerwagen: ''
  migne: ''
  title: In Marci euangelium expositio
CMF:
  abbreviation: CMF
  editions: 
    - giles: '1.198-202'
  heerwagen: ''
  migne: ''
  title: De mansionibus filiorum Israel
CPr:
  abbreviation: CPr
  editions: 
    - giles: 9.53-185
  title: In Prouerbia Salemonis
CPs:
  abbreviation: CPs
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: Collectio Psalterii
CQO:
  abbreviation: CQO
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: De octo quaestionibus
CQT:
  abbreviation: CQT
  editions: 
    - giles: 1.174-75 and 8.232-61
  title: In Regum librum XXX quaestiones
CS:
  abbreviation: CS
  editions: 
    - giles: 7.368-432 and 8.1-231
  title: In primam partem Samuhelis
CTa:
  abbreviation: CTa
  editions: 
    - giles: 7.225-367
  title: De tabernaculo
CTe:
  abbreviation: CTe
  editions: 
    - giles: 1.171-73 and 8.262-359
  title: De templo
CTo:
  abbreviation: CTo
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: 'In librum beati patris Tobiae '
ChMa:
  abbreviation: ChMa
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: Chronica maiora
ChMi:
  abbreviation: ChMi
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: Chronica minora
DAM:
  abbreviation: DAM
  editions: 
    - giles: 6.40-79
  title: De arte metrica
DLS:
  abbreviation: DLS
  editions: 
    - giles: 4.402-443
  title: De locis sanctis
DNR:
  abbreviation: DNR
  editions: 
    - giles: 6.99-122
  title: De natura rerum
DO:
  abbreviation: DO
  editions: 
    - giles: 6.1-39
  title: De orthographia
DST:
  abbreviation: DST
  editions: 
    - giles: 6.80-98
  title: De schematibus et tropis
DT:
  abbreviation: DT
  editions: 
    - giles: 6.123-38
  title: De temporibus
DTR:
  abbreviation: DTR
  editions: 
    - giles: 6.139-352
  title: De temporum ratione
EpA:
  abbreviation: EpA
  editions: 
    - giles: '1.106-7'
  heerwagen: ''
  migne: ''
  title: Epistula ad Albinum
EpE:
  abbreviation: EpE
  editions: 
    - giles: '1.108-143'
  heerwagen: ''
  migne: ''
  title: Epistula ad Ecgbertum
EpH:
  abbreviation: EpH
  editions: 
    - giles: ''
  heerwagen: ''
  migne: ''
  title: Epistula ad Helmuualdum
EpP:
  abbreviation: EpP
  editions: 
    - giles: '1.144-154'
  heerwagen: ''
  migne: ''
  title: Epistula ad Pleguinum
EpW:
  abbreviation: EpW
  editions: 
    - giles: '1.155-168'
  heerwagen: ''
  migne: ''
  title: Epistula ad Uuicthedum
H:
  abbreviation: H
  editions: 
    - giles: 5.1-464
  title: Homiliae euangelii
HAB:
  abbreviation: HAB
  editions: 
    - giles: 4.358-401
  title: Historia abbatum
HE:
  abbreviation: HE
  editions: 
    - giles: 2.22-397 and 3.4-319 (odd) 
  title: Historia ecclesiastica gentis Anglorum
  notes: Giles 2.25-26 superseded by 3.s447-48
M:
  abbreviation: M
  editions: 
    - giles: 4.16-172
  title: Martyrologium
P:
  abbreviation: P
  editions: []
  title: Poems
VA:
  abbreviation: VA
  editions: []
  title: Passio Anastasii
VCM:
  abbreviation: VCM
  editions: 
    - giles: 1.1-34
  title: Vita Cuthberti metrica
VCP:
  abbreviation: VCP
  editions: 
    - giles: 4.202-357
  title: Vita Cuthberti prosaica
VF:
  abbreviation: VF
  editions: 
    - giles: 4.174-201
  title: Vita Felicis
